{% set name = "async_retriever" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/async_retriever-{{ version }}.tar.gz
  sha256: 5d7314cf64a018f896741d03890f53d22bd3b1b844b2ecb59ccca3cc53005d93

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - aiohttp
    - aiohttp-client-cache
    - aiosqlite
    - cytoolz
    - nest-asyncio
    - orjson
    - python >=3.7

test:
  imports:
    - async_retriever
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cheginit/async_retriever
  summary: High-level API for asynchronous requests with persistent caching.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
