{% set name = "async_retriever" %}
{% set version = "0.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/async_retriever-{{ version }}.tar.gz
  sha256: acfc1e70a2b9c933ae2f870e0fb403835ddd791df357e5927d2e735a3972d011

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - aiodns
    - aiohttp
    - aiohttp-client-cache
    - aiosqlite
    - brotlipy
    - cchardet
    - cytoolz
    - nest-asyncio
    - orjson
    - python >=3.7

test:
  imports:
    - async_retriever
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cheginit/async_retriever
  summary: High-level API for asynchronous requests with persistent caching.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
