{% set name = "async-retriever" %}
{% set version = "0.3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/async_retriever-{{ version }}.tar.gz
  sha256: 319d63f05c1b077f6c10ab1e1f890d43579098cce85edfcea556c3280b9c68c7

build:
  number: 0

outputs:
  - name: {{ name }}
    build:
      noarch: python
    script: build_base.sh
    requirements:
      host:
        - python >=3.8
        - pip
        - setuptools-scm
      run:
        - python >=3.8
        - cytoolz
        - nest-asyncio
        - aiohttp-client-cache >=0.8.1
        - ujson
        - cytoolz

    test:
      imports:
        - async_retriever
      commands:
        - pip check
      requires:
        - pip

  - name: async_retriever
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage('async-retriever', max_pin="x.x.x") }}
    test:
      imports:
        - async_retriever

about:
  home: https://github.com/hyriver/async-retriever
  summary: High-level API for asynchronous requests with persistent caching.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
