{% set name = "async_retriever" %}
{% set version = "0.2.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/async_retriever-{{ version }}.tar.gz
  sha256: b3b8c1dc565a3a647bb2c5311d714faf5643bd70ff6b974dc924866c1cb856ae

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - aiodns
    - aiohttp
    - aiohttp-client-cache
    - aiosqlite
    - brotlipy
    - cchardet
    - cytoolz
    - nest-asyncio
    - python >=3.7
    - ujson

test:
  imports:
    - async_retriever
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cheginit/async_retriever
  summary: High-level API for asynchronous requests with persistent caching.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
