{% set name = "async_retriever" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/async_retriever-{{ version }}.tar.gz
  sha256: 992a367c536439f9768f7ba783a971e94e228f277e36251fc19043b56a290be4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - aiodns
    - aiohttp
    - aiohttp-client-cache >=0.5.1
    - aiosqlite
    - brotlipy
    - cchardet
    - cytoolz
    - importlib_metadata
    - nest-asyncio
    - python >=3.7
    - ujson

test:
  imports:
    - async_retriever
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cheginit/async_retriever
  summary: High-level API for asynchronous requests with persistent caching.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
