{% set name = "async-retriever" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 784751df9e46cd59711f7fdedd5e521cffba1b0758f577544171d74d48d096d9

build:
  number: 0

outputs:
  - name: {{ name }}
    build:
      noarch: python
    script: build_base.sh
    requirements:
      host:
        - python >=3.8
        - setuptools >=42
        - setuptools-scm >=7
        - pip
      run:
        - python >=3.8
        - aiodns
        - aiohttp-client-cache >=0.8.1
        - brotli
        - cytoolz
        - nest-asyncio
        - ujson

    test:
      imports:
        - async_retriever
      commands:
        - pip check
      requires:
        - pip

  - name: async_retriever
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage(name, exact=True) }}
    test:
      imports:
        - async_retriever

about:
  home: https://github.com/hyriver/async-retriever
  summary: High-level API for asynchronous requests with persistent caching.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
