{% set name = "async_retriever" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/async_retriever-{{ version }}.tar.gz
  sha256: 472667534fbd295867b76cf762412bf97702f0ec19a857326fabac86fc98cb66

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - aiodns
    - aiohttp >=3.8.1
    - aiohttp-client-cache >=0.6.1
    - aiosqlite
    - brotli
    - cchardet
    - cytoolz
    - nest-asyncio
    - python >=3.8
    - ujson

test:
  imports:
    - async_retriever
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hyriver/async_retriever
  summary: High-level API for asynchronous requests with persistent caching.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
